name: feature_play_style
description: "A playStyle feature package that holds its own business logic and UI."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  core_api_client:
    path: ../../../packages/core/api_client
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  utility_di:
    path: ../../../packages/utility/di
  utility_navigation:
    path: ../../../packages/utility/navigation

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
