name: utility_di
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
