name: utility_di
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.1"

dependencies:
  flutter:
    sdk: flutter
  get_it: 8.0.3
  injectable: 2.5.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: 2.7.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
