name: eed_app

packages:
  - /**

scripts:
  analyze:
    run: melos exec -c 1 -- fvm flutter analyze .
    description: Run `flutter analyze` in all packages.

  get:
    run: melos exec -c 1 -- fvm flutter pub get
    description: Run `flutter pub get` in all packages.