name: eed_app

packages:
  - /
  - packages/**

scripts:
  install:
    description: Run install script
    run: |
      sh scripts/install.sh
      melos run get

  analyze:
    run: melos exec -c 1 -- flutter analyze .
    description: Run `flutter analyze` in all packages.

  get:
    run: melos exec -c 1 -- flutter pub get
    description: Run `flutter pub get` in all packages.

  fix:
    description: Run `dart fix` in all packages
    run: melos exec -c 1 -- dart fix --apply

  format:
    description: Run `dart format` in all packages
    run: melos exec -c 1 -- dart format .

  outdated:
    description: Run `flutter pub outdated` in all packages
    run: melos exec -c 1 -- flutter pub outdated

  upgrade:
    description: Run `flutter pub upgrade` in all packages
    run: melos exec -c 1 -- flutter pub upgrade

  upgrade_major_versions:
    description: Run `flutter pub upgrade` in all packages
    run: melos exec -c 1 -- flutter pub upgrade --major-versions