name: fc_concept
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  cached_network_image: ^3.3.1
  core_ads:
    path: packages/core/ads
  core_api_client:
    path: packages/core/api_client
  core_design:
    path: packages/core/design
  core_domain:
    path: packages/core/domain
  cupertino_icons: ^1.0.6
  feature_auth:
    path: packages/features/auth
  feature_compare:
    path: packages/features/compare
  feature_dashboard:
    path: packages/features/dashboard
  feature_filter:
    path: packages/features/filter
  feature_menu:
    path: packages/features/menu
  feature_player:
    path: packages/features/player
  flutter:
    sdk: flutter
  injectable: ^2.3.2
  utility_catalog:
    path: packages/utility/catalog
  utility_di:
    path: packages/utility/di
  utility_navigation:
    path: packages/utility/navigation

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
  melos: ^6.1.0
  utility_analysis:
    path: packages/utility/analysis

flutter:
  uses-material-design: true
