name: core_domain
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  cached_annotation: ^1.7.0
  collection: ^1.18.0
  core_api_client:
    path: ../../../packages/core/api_client
  dart_mappable: ^4.2.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  supabase_flutter: ^2.5.6
  utility_di:
    path: ../../../packages/utility/di
  utility_extensions:
    path: ../../../packages/utility/extensions

dev_dependencies:
  build_runner: ^2.4.9
  cached: 1.7.0
  dart_mappable_builder: ^4.2.3
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
