name: feature_filter
description: "Filter feature"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  collection: ^1.18.0
  core_analytics:
    path: ../../../packages/core/analytics
  core_api_client:
    path: ../../../packages/core/api_client
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  utility_di:
    path: ../../../packages/utility/di
  utility_navigation:
    path: ../../../packages/utility/navigation

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.4.2
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
