name: core_api_client
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.1"

dependencies:
  dio: 5.8.0+1
  dio_cache_interceptor: 4.0.2
  http_cache_hive_store: 5.0.1
  hive: ^2.2.3
  flutter:
    sdk: flutter
  injectable: 2.5.0
  supabase_flutter: 2.9.1
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: 2.7.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
