name: core_api_client
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  dio: 5.4.1
  flutter:
    sdk: flutter
  injectable: ^2.3.2
  supabase_flutter: ^1.5.0
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
