import 'package:core_domain/domain.dart';

class RarityColor {
  const RarityColor(
    this.id,
    this.bg,
    this.fg,
  );

  final int id;
  final int bg;
  final int fg;
}

const rarityColorMap = {
  0: RarityColor(0, nonRareBg, nonRareFg),
  1: RarityColor(1, rareBg, rareFg),
  3: RarityColor(3, totwBg, totwFg),
  4: RarityColor(4, heroBg, heroFg),
  5: RarityColor(5, totyBg, totyFg),
  7: RarityColor(7, punditPicksBg, punditPicksFg),
  11: RarityColor(11, totsBg, totsFg),
  12: RarityColor(12, iconsBg, iconsFg),
  22: RarityColor(22, trailblazersBg, trailblazersFg),
  24: RarityColor(24, sbcBg, sbcFg),
  25: RarityColor(25, premiumSbcBg, premiumSbcFg),
  28: RarityColor(28, tripleThreatBg, tripleThreatFg),
  30: RarityColor(30, futBirthdayBg, futBirthdayFg),
  31: RarityColor(31, womenCLRttkBg, womenCLRttfFg),
  32: RarityColor(32, womenCLRttfBg, womenCLRttfFg),
  34: RarityColor(34, fcProBg, fcProFg),
  35: RarityColor(35, winterWildcardsBg, winterWildcardsFg),
  37: RarityColor(37, radioactiveBg, radioactiveFg),
  42: RarityColor(42, potmBundesligaBg, potmBundesligaFg),
  43: RarityColor(43, potmPremierLeagueBg, potmPremierLeagueFg),
  46: RarityColor(46, ueclRTTKBg, ueclRTTKFg),
  50: RarityColor(50, uclRTTKBg, uclRTTKFg),
  51: RarityColor(51, flashbackSbcBg, flashbackSbcFg),
  52: RarityColor(52, sudamericanaBg, sudamericanaFg),
  53: RarityColor(53, libertadoresBg, libertadoresFg),
  55: RarityColor(55, futureStarsAcademyBg, futureStarsAcademyFg),
  57: RarityColor(57, showdownUpgradeBg, showdownUpgradeFg),
  58: RarityColor(58, showdownBg, showdownFg),
  64: RarityColor(64, totyHonourableBg, totyHonourableFg),
  68: RarityColor(68, uclTotgsBg, uclTotgsFg),
  69: RarityColor(69, uelTotgsBg, uelTotgsFg),
  70: RarityColor(70, ueclTotgsBg, ueclTotgsFg),
  71: RarityColor(71, futureStarsBg, futureStarsFg),
  72: RarityColor(72, uefaHeroesBg, uefaHeroesFg),
  79: RarityColor(79, potmLigue1Bg, potmLigue1Fg),
  80: RarityColor(80, fcProUpgradeBg, fcProUpgradeFg),
  81: RarityColor(81, beatsBg, beatsFg),
  82: RarityColor(82, tripleThreatHeroBg, tripleThreatHeroFg),
  84: RarityColor(84, dynastiesBg, dynastiesFg),
  85: RarityColor(85, dynastiesIconBg, dynastiesIconFg),
  86: RarityColor(86, potmLaLigaBg, potmLaLigaFg),
  87: RarityColor(87, squadFoundationBg, squadFoundationFg),
  90: RarityColor(90, playerMomentsBg, playerMomentsFg),
  91: RarityColor(91, objectiveRewardStorylineBg, objectiveRewardStorylineFg),
  95: RarityColor(95, headlinersBg, headlinersFg),
  105: RarityColor(105, ueclRTTKBg, ueclRTTKFg),
  108: RarityColor(108, versusIceBg, versusIceFg),
  111: RarityColor(111, fantasyFCBg, fantasyFCFg),
  114: RarityColor(114, potmSerieABg, potmSerieAFg),
  115: RarityColor(115, potmEredivisieBg, potmEredivisieFg),
  116: RarityColor(116, versusFireBg, versusFireFg),
  117: RarityColor(117, winterWildcardsBg, winterWildcardsFg),
  118: RarityColor(118, winterWildcardsBg, winterWildcardsFg),
  123: RarityColor(123, euroBg, euroFg),
  124: RarityColor(124, uclRttfBg, uclRttfFg),
  125: RarityColor(125, uelRttfBg, uelRttfFg),
  126: RarityColor(126, ueclRttfBg, ueclRttfFg),
  135: RarityColor(135, fantasyHeroBg, fantasyHeroFg),
  149: RarityColor(149, futBirthdayIconBg, futBirthdayIconFg),
  150: RarityColor(150, dynamicDuosBg, dynamicDuosFg),
  151: RarityColor(151, futCenturionsBg, futCenturionsFg),
  152: RarityColor(152, futBirthdayIconBg, futBirthdayIconFg),
  155: RarityColor(155, totyIconBg, totyIconFg),
  157: RarityColor(157, thunderstruckIconBg, thunderstruckIconFg),
  160: RarityColor(160, golazoHeroBg, golazoHeroFg),
  161: RarityColor(161, golazoIconBg, golazoIconFg),
  168: RarityColor(168, centurionsIconBg, centurionsIconFg),
  170: RarityColor(170, futureStarsIconBg, futureStarsIconFg),
  171: RarityColor(171, championsLeagueHeroBg, championsLeagueHeroFg),
  172: RarityColor(172, uefaHeroesBg, uefaHeroesFg),
  182: RarityColor(182, nikeMADReadyBg, nikeMADReadyFg),
};