name: utility_catalog
description: "A Catalog for design system"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.1"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
