name: core_design
description: "Design System"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  core_api_client:
    path: ../../../packages/core/api_client
  core_domain:
    path: ../../../packages/core/domain
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  intersperse: ^2.0.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  utility_extensions:
    path: ../../../packages/utility/extensions

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/atoms
  assets:
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true
  integrations:
    flutter_svg: true

