name: core_design
description: "Design System"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.6"

dependencies:
  core_api_client:
    path: ../../../packages/core/api_client
  core_domain:
    path: ../../../packages/core/domain
  cached_network_image: 3.4.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  google_fonts: 6.2.1
  intersperse: ^2.0.0
  intl: 0.20.2
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  stream_transform: 2.1.1
  utility_extensions:
    path: ../../../packages/utility/extensions

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: 5.10.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/atoms
  assets:
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true
  integrations:
    flutter_svg: true

