name: feature_menu
description: "Drawers"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.1"

dependencies:
  core_analytics:
    path: ../../../packages/core/analytics
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  dart_mappable: 4.5.0
  feature_auth:
    path: ../../../packages/features/auth
  feature_compare:
    path: ../../../packages/features/compare
  feature_player:
    path: ../../../packages/features/player
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  flutter_markdown: 0.7.6+2
  injectable: 2.5.0
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: 2.4.15
  dart_mappable_builder: 4.5.0
  injectable_generator: 2.7.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
