name: feature_player
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  bloc_concurrency: ^0.2.5
  core_api_client:
    path: ../../../packages/core/api_client
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  feature_drawer:
    path: ../../../packages/features/drawer
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  stream_transform: ^2.1.0
  utility_di:
    path: ../../../packages/utility/di
  utility_navigation:
    path: ../../../packages/utility/navigation

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
