name: feature_drawer
description: "Drawers"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  core_design:
    path: ../../../packages/core/design
  core_domain:
    path: ../../../packages/core/domain
  dart_mappable: ^4.2.2
  feature_compare:
    path: ../../../packages/features/compare
  feature_player:
    path: ../../../packages/features/player
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  injectable: ^2.3.2
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  injectable_generator: ^2.4.1
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
