export 'package:core_analytics/src/analytics_event_name.dart';
export 'package:core_analytics/src/di/injector.dart';
export 'package:core_analytics/src/feedback/wiredash_feedback.dart';
export 'package:core_analytics/src/feedback/wiredash_theme.dart';
export 'package:core_analytics/src/model/analytics_event_parameters.dart';
export 'package:core_analytics/src/use_case/log_event_use_case.dart';
export 'package:firebase_analytics/firebase_analytics.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:wiredash/wiredash.dart';
