name: core_ads
description: "Ads package"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  bloc_concurrency: ^0.2.5
  core_design:
    path: ../../../packages/core/design
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  google_mobile_ads: 5.2.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  utility_di:
    path: ../../../packages/utility/di
  utility_navigation:
    path: ../../../packages/utility/navigation

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  injectable_generator: ^2.4.2
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
