name: utility_navigation
description: "A utility package for navigation in the app"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.6"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  injectable: 2.5.0
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: ^2.5.4
  injectable_generator: 2.7.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
