name: utility_navigation
description: "A utility package for navigation in the app"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: "3.29.2"

dependencies:
  flutter:
    sdk: flutter
  go_router: 14.8.1
  injectable: 2.5.0
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: 2.4.15
  injectable_generator: 2.7.0
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
