name: utility_navigation
description: "A utility package for navigation in the app"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  injectable: ^2.3.2
  utility_di:
    path: ../../../packages/utility/di

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.4.1
  utility_analysis:
    path: ../../../packages/utility/analysis

flutter:
